const { afterEach, describe, expect, test } = require('bun:test')
const fs = require('fs')
const os = require('os')
const path = require('path')
const plugin = require('../app.plugin')
const {
  buildUiTestScheme,
  copyCompanionFiles,
  inferProjectName,
  scaffoldCompanion,
} = require('./scaffold')

const tempDirs = []

function tempDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'rn-driver-xctest-'))
  tempDirs.push(dir)
  return dir
}

afterEach(() => {
  while (tempDirs.length > 0) {
    fs.rmSync(tempDirs.pop(), { recursive: true, force: true })
  }
})

describe('XCTest companion scaffold helpers', () => {
  test('app plugin exports the companion config plugin and scaffold helper', () => {
    expect(typeof plugin).toBe('function')
    expect(plugin.scaffoldCompanion).toBe(scaffoldCompanion)
  })

  test('copies companion Swift files into the UI test folder', () => {
    const testsDir = path.join(tempDir(), 'ExampleUITests')

    copyCompanionFiles(testsDir)

    expect(fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanion.swift'))).toBe(true)
    expect(fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanionTests.swift'))).toBe(true)
    expect(fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanionRuntimeConfig.json'))).toBe(
      true,
    )
    expect(
      fs.readFileSync(path.join(testsDir, 'RNDriverTouchCompanion.README.md'), 'utf8'),
    ).toContain('generated by @unrulysystems/rn-playwright-driver-xctest-companion')
  })

  test('copied XCTest runner supports host-launched attach mode', () => {
    const testsDir = path.join(tempDir(), 'ExampleUITests')

    copyCompanionFiles(testsDir)

    const runner = fs.readFileSync(path.join(testsDir, 'RNDriverTouchCompanionTests.swift'), 'utf8')
    expect(runner).toContain('private enum LaunchMode: String')
    expect(runner).toContain('environment["RN_TOUCH_XCTEST_LAUNCH"]')
    expect(runner).toContain('payload["launchMode"] ?? payload["launch"]')
    expect(runner).toContain('case .attach:')
    expect(runner).toContain('should not be relaunched by XCTest')
  })

  test('infers project name from an xcodeproj directory', () => {
    const iosDir = tempDir()
    fs.mkdirSync(path.join(iosDir, 'Example.xcodeproj'))

    expect(inferProjectName(iosDir)).toBe('Example')
  })

  test('scaffolds files when the Xcode project has not been generated yet', () => {
    const iosDir = tempDir()

    const result = scaffoldCompanion({ iosDir, projectName: 'Example' })

    expect(result).toEqual({
      projectName: 'Example',
      uiTestTargetName: 'ExampleUITests',
      testsDir: path.join(iosDir, 'ExampleUITests'),
    })
    expect(fs.existsSync(path.join(iosDir, 'ExampleUITests', 'RNDriverTouchCompanion.swift'))).toBe(
      true,
    )
    expect(
      fs.existsSync(
        path.join(iosDir, 'ExampleUITests', 'RNDriverTouchCompanionRuntimeConfig.json'),
      ),
    ).toBe(true)
  })

  test('generates a shared UI test scheme with target UUIDs', () => {
    const scheme = buildUiTestScheme({
      appTargetName: 'Example',
      appTargetUuid: 'APP_TARGET_UUID',
      uiTestTargetName: 'ExampleUITests',
      uiTestTargetUuid: 'UITEST_TARGET_UUID',
    })

    expect(scheme).toContain('BuildableName = "Example.app"')
    expect(scheme).toContain('BuildableName = "ExampleUITests.xctest"')
    expect(scheme).toContain('BlueprintIdentifier = "APP_TARGET_UUID"')
    expect(scheme).toContain('BlueprintIdentifier = "UITEST_TARGET_UUID"')
    expect(scheme).toContain('ReferencedContainer = "container:Example.xcodeproj"')
  })
})
