const assert = require('node:assert/strict')
const { afterEach, describe, test } = require('node:test')
const fs = require('fs')
const os = require('os')
const path = require('path')
const plugin = require('../app.plugin')
const {
  buildUiTestScheme,
  copyCompanionFiles,
  inferProjectName,
  scaffoldCompanion,
} = require('./scaffold')

const tempDirs = []

function tempDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'rn-driver-xctest-'))
  tempDirs.push(dir)
  return dir
}

afterEach(() => {
  while (tempDirs.length > 0) {
    fs.rmSync(tempDirs.pop(), { recursive: true, force: true })
  }
})

describe('XCTest companion scaffold helpers', () => {
  test('app plugin exports the companion config plugin and scaffold helper', () => {
    assert.equal(typeof plugin, 'function')
    assert.equal(plugin.scaffoldCompanion, scaffoldCompanion)
  })

  test('copies companion Swift files into the UI test folder', () => {
    const testsDir = path.join(tempDir(), 'ExampleUITests')

    copyCompanionFiles(testsDir)

    assert.equal(fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanion.swift')), true)
    assert.equal(fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanionTests.swift')), true)
    assert.equal(
      fs.existsSync(path.join(testsDir, 'RNDriverTouchCompanionRuntimeConfig.json')),
      true,
    )
    assert.equal(
      fs
        .readFileSync(path.join(testsDir, 'RNDriverTouchCompanion.README.md'), 'utf8')
        .includes('generated by @unrulysystems/rn-playwright-driver-xctest-companion'),
      true,
    )
  })

  test('copied XCTest runner supports host-launched attach mode', () => {
    const testsDir = path.join(tempDir(), 'ExampleUITests')

    copyCompanionFiles(testsDir)

    const runner = fs.readFileSync(path.join(testsDir, 'RNDriverTouchCompanionTests.swift'), 'utf8')
    assert.equal(runner.includes('private enum LaunchMode: String'), true)
    assert.equal(runner.includes('environment["RN_TOUCH_XCTEST_LAUNCH"]'), true)
    assert.equal(runner.includes('payload["launchMode"] ?? payload["launch"]'), true)
    assert.equal(runner.includes('case .attach:'), true)
    assert.equal(runner.includes('should not be relaunched by XCTest'), true)
  })

  test('infers project name from an xcodeproj directory', () => {
    const iosDir = tempDir()
    fs.mkdirSync(path.join(iosDir, 'Example.xcodeproj'))

    assert.equal(inferProjectName(iosDir), 'Example')
  })

  test('scaffolds files when the Xcode project has not been generated yet', () => {
    const iosDir = tempDir()

    const result = scaffoldCompanion({ iosDir, projectName: 'Example' })

    assert.deepEqual(result, {
      projectName: 'Example',
      uiTestTargetName: 'ExampleUITests',
      testsDir: path.join(iosDir, 'ExampleUITests'),
    })
    assert.equal(
      fs.existsSync(path.join(iosDir, 'ExampleUITests', 'RNDriverTouchCompanion.swift')),
      true,
    )
    assert.equal(
      fs.existsSync(
        path.join(iosDir, 'ExampleUITests', 'RNDriverTouchCompanionRuntimeConfig.json'),
      ),
      true,
    )
  })

  test('generates a shared UI test scheme with target UUIDs', () => {
    const scheme = buildUiTestScheme({
      appTargetName: 'Example',
      appTargetUuid: 'APP_TARGET_UUID',
      uiTestTargetName: 'ExampleUITests',
      uiTestTargetUuid: 'UITEST_TARGET_UUID',
    })

    assert.equal(scheme.includes('BuildableName = "Example.app"'), true)
    assert.equal(scheme.includes('BuildableName = "ExampleUITests.xctest"'), true)
    assert.equal(scheme.includes('BlueprintIdentifier = "APP_TARGET_UUID"'), true)
    assert.equal(scheme.includes('BlueprintIdentifier = "UITEST_TARGET_UUID"'), true)
    assert.equal(scheme.includes('ReferencedContainer = "container:Example.xcodeproj"'), true)
  })
})
