const fs = require('fs')
const path = require('path')
const xcode = require('xcode')

const SERVER_FILE = 'RNDriverTouchCompanion.swift'
const TEST_FILE = 'RNDriverTouchCompanionTests.swift'
const RUNTIME_CONFIG_FILE = 'RNDriverTouchCompanionRuntimeConfig.json'
const GENERATED_README = 'RNDriverTouchCompanion.README.md'
const UI_TEST_PRODUCT_TYPE = 'com.apple.product-type.bundle.ui-testing'

function scaffoldCompanion(options) {
  const iosDir = path.resolve(options.iosDir)
  const projectName = options.projectName || inferProjectName(iosDir)
  if (!projectName) {
    throw new Error(`Could not infer project name from ${iosDir}; pass --project-name`)
  }

  const uiTestTargetName = options.uiTestTargetName || `${projectName}UITests`
  const testsDir = path.join(iosDir, uiTestTargetName)

  copyCompanionFiles(testsDir)
  const projectPath = path.join(iosDir, `${projectName}.xcodeproj`, 'project.pbxproj')
  if (fs.existsSync(projectPath)) {
    const targetInfo = ensureUiTestTarget({ projectPath, projectName, uiTestTargetName })
    writeSharedScheme({ iosDir, projectName, ...targetInfo })
  }

  return { projectName, uiTestTargetName, testsDir }
}

function inferProjectName(iosDir) {
  if (!fs.existsSync(iosDir)) {
    return undefined
  }

  const entries = fs.readdirSync(iosDir)
  const project = entries.find((entry) => entry.endsWith('.xcodeproj'))
  return project ? project.replace(/\.xcodeproj$/, '') : undefined
}

function copyCompanionFiles(testsDir) {
  fs.mkdirSync(testsDir, { recursive: true })

  const sourceDir = path.join(__dirname, '../ios')
  fs.copyFileSync(path.join(sourceDir, SERVER_FILE), path.join(testsDir, SERVER_FILE))
  fs.copyFileSync(path.join(sourceDir, TEST_FILE), path.join(testsDir, TEST_FILE))
  fs.copyFileSync(
    path.join(sourceDir, RUNTIME_CONFIG_FILE),
    path.join(testsDir, RUNTIME_CONFIG_FILE),
  )
  fs.writeFileSync(
    path.join(testsDir, GENERATED_README),
    [
      '# RN Driver XCTest Companion',
      '',
      'These files are generated by @unrulysystems/rn-playwright-driver-xctest-companion.',
      '',
      'The scaffold creates/updates a shared UI test scheme so host-side e2e scripts can run RNDriverTouchCompanionTests/testRunServer.',
      '',
    ].join('\n'),
  )
}

function ensureUiTestTarget({ projectPath, projectName, uiTestTargetName }) {
  const project = xcode.project(projectPath)
  project.parseSync()

  const appTarget = findNativeTargetByName(project, projectName) || firstApplicationTarget(project)
  if (!appTarget) {
    throw new Error(`Could not find app target '${projectName}' in ${projectPath}`)
  }

  const existingTarget = findNativeTargetByName(project, uiTestTargetName)
  const target = existingTarget || project.addTarget(uiTestTargetName, 'unit_test_bundle')
  const targetUuid = existingTarget ? existingTarget.uuid : target.uuid
  const nativeTarget = existingTarget ? existingTarget.target : target.pbxNativeTarget
  nativeTarget.productType = `"${UI_TEST_PRODUCT_TYPE}"`
  normalizeUiTestProductReference(project, nativeTarget, uiTestTargetName)
  removeTargetDependency(project, appTarget.uuid, targetUuid)

  ensureBuildPhases(project, targetUuid)
  patchBuildSettings(project, {
    appBundleId: getBundleIdentifier(project, appTarget.target) || projectName,
    appTargetName: trimQuotes(appTarget.target.name),
    targetName: uiTestTargetName,
    targetUuid,
  })

  const groupKey = ensureGroup(project, uiTestTargetName)
  for (const file of [SERVER_FILE, TEST_FILE]) {
    const relativePath = `${uiTestTargetName}/${file}`
    if (!hasSourceFile(project, file, relativePath)) {
      project.addSourceFile(file, { target: targetUuid }, groupKey)
    }
    normalizeGroupedFile(project, file, relativePath)
  }
  const runtimeConfigRelativePath = `${uiTestTargetName}/${RUNTIME_CONFIG_FILE}`
  if (!hasSourceFile(project, RUNTIME_CONFIG_FILE, runtimeConfigRelativePath)) {
    ensureGroup(project, 'Resources')
    project.addResourceFile(RUNTIME_CONFIG_FILE, { target: targetUuid }, groupKey)
  }
  normalizeGroupedFile(project, RUNTIME_CONFIG_FILE, runtimeConfigRelativePath)

  fs.writeFileSync(projectPath, project.writeSync())
  return {
    appTargetUuid: appTarget.uuid,
    uiTestTargetName,
    uiTestTargetUuid: targetUuid,
  }
}

function normalizeUiTestProductReference(project, nativeTarget, uiTestTargetName) {
  const productReference = nativeTarget.productReference
  if (!productReference) {
    return
  }

  const fileReference = project.pbxFileReferenceSection()[productReference]
  if (!fileReference) {
    return
  }

  fileReference.explicitFileType = 'wrapper.cfbundle'
  fileReference.name = `${uiTestTargetName}.xctest`
  fileReference.path = `${uiTestTargetName}.xctest`
  delete fileReference.lastKnownFileType
}

function normalizeGroupedFile(project, fileName, relativePath) {
  for (const fileReference of Object.values(project.pbxFileReferenceSection())) {
    if (!fileReference || typeof fileReference !== 'object') {
      continue
    }
    if (fileReference.name !== fileName && fileReference.path !== relativePath) {
      continue
    }
    fileReference.name = fileName
    fileReference.path = fileName
  }
}

function firstApplicationTarget(project) {
  const entry = Object.entries(project.pbxNativeTargetSection()).find(
    ([key, target]) =>
      !key.endsWith('_comment') &&
      trimQuotes(target.productType) === 'com.apple.product-type.application',
  )
  return entry ? { uuid: entry[0], target: entry[1] } : undefined
}

function findNativeTargetByName(project, name) {
  const entry = Object.entries(project.pbxNativeTargetSection()).find(
    ([key, target]) => !key.endsWith('_comment') && trimQuotes(target.name) === name,
  )
  return entry ? { uuid: entry[0], target: entry[1] } : undefined
}

function ensureBuildPhases(project, targetUuid) {
  const target = project.pbxNativeTargetSection()[targetUuid]
  const phaseNames = new Set((target.buildPhases || []).map((phase) => phase.comment))
  if (!phaseNames.has('Sources')) {
    project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', targetUuid)
  }
  if (!phaseNames.has('Frameworks')) {
    project.addBuildPhase([], 'PBXFrameworksBuildPhase', 'Frameworks', targetUuid)
  }
  if (!phaseNames.has('Resources')) {
    project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', targetUuid)
  }
}

function removeTargetDependency(project, targetUuid, dependencyTargetUuid) {
  const target = project.pbxNativeTargetSection()[targetUuid]
  if (!target?.dependencies) {
    return
  }

  const dependencies = project.hash.project.objects.PBXTargetDependency || {}
  target.dependencies = target.dependencies.filter((dependencyRef) => {
    const dependency = dependencies[dependencyRef.value]
    return dependency?.target !== dependencyTargetUuid
  })
}

function patchBuildSettings(project, { appBundleId, appTargetName, targetName, targetUuid }) {
  const target = project.pbxNativeTargetSection()[targetUuid]
  const configurationList = project.pbxXCConfigurationList()[target.buildConfigurationList]
  for (const configRef of configurationList.buildConfigurations) {
    const config = project.pbxXCBuildConfigurationSection()[configRef.value]
    config.buildSettings = {
      ...config.buildSettings,
      CODE_SIGN_STYLE: 'Automatic',
      GENERATE_INFOPLIST_FILE: 'YES',
      LD_RUNPATH_SEARCH_PATHS:
        '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
      PRODUCT_BUNDLE_IDENTIFIER: `"${trimQuotes(appBundleId)}.${targetName}"`,
      PRODUCT_NAME: '"$(TARGET_NAME)"',
      SDKROOT: 'iphoneos',
      SWIFT_VERSION: '5.0',
      TARGETED_DEVICE_FAMILY: '"1,2"',
      TEST_TARGET_NAME: `"${appTargetName}"`,
    }
    delete config.buildSettings.INFOPLIST_FILE
  }
}

function getBundleIdentifier(project, appTarget) {
  const configurationList = project.pbxXCConfigurationList()[appTarget.buildConfigurationList]
  const firstConfigRef = configurationList.buildConfigurations[0]
  const config = project.pbxXCBuildConfigurationSection()[firstConfigRef.value]
  return config?.buildSettings?.PRODUCT_BUNDLE_IDENTIFIER
}

function ensureGroup(project, groupName) {
  const existing = project.pbxGroupByName(groupName)
  if (existing) {
    return findGroupKey(project, existing)
  }

  const groupKey = project.pbxCreateGroup(groupName, groupName)
  const mainGroup = project.getPBXGroupByKey(project.getFirstProject().firstProject.mainGroup)
  mainGroup.children.push({ value: groupKey, comment: groupName })
  return groupKey
}

function findGroupKey(project, group) {
  const entry = Object.entries(project.hash.project.objects.PBXGroup).find(
    ([key, value]) => !key.endsWith('_comment') && value === group,
  )
  if (!entry) {
    throw new Error('Could not resolve PBXGroup key for XCTest companion group')
  }
  return entry[0]
}

function hasSourceFile(project, fileName, relativePath) {
  return Boolean(project.hasFile(fileName) || project.hasFile(relativePath))
}

function writeSharedScheme({
  iosDir,
  projectName,
  appTargetUuid = projectName,
  uiTestTargetName,
  uiTestTargetUuid = uiTestTargetName,
}) {
  const schemesDir = path.join(iosDir, `${projectName}.xcodeproj`, 'xcshareddata', 'xcschemes')
  fs.mkdirSync(schemesDir, { recursive: true })
  fs.writeFileSync(
    path.join(schemesDir, `${uiTestTargetName}.xcscheme`),
    buildUiTestScheme({
      appTargetName: projectName,
      appTargetUuid,
      uiTestTargetName,
      uiTestTargetUuid,
    }),
  )
}

function buildUiTestScheme({
  appTargetName,
  appTargetUuid = appTargetName,
  uiTestTargetName,
  uiTestTargetUuid = uiTestTargetName,
}) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "1540"
   version = "1.7">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "NO"
            buildForArchiving = "NO"
            buildForAnalyzing = "YES">
            ${buildableReference({ targetName: appTargetName, targetUuid: appTargetUuid, buildableName: `${appTargetName}.app`, projectName: appTargetName })}
         </BuildActionEntry>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "NO"
            buildForProfiling = "NO"
            buildForArchiving = "NO"
            buildForAnalyzing = "YES">
            ${buildableReference({ targetName: uiTestTargetName, targetUuid: uiTestTargetUuid, buildableName: `${uiTestTargetName}.xctest`, projectName: appTargetName })}
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      shouldUseLaunchSchemeArgsEnv = "YES">
      <Testables>
         <TestableReference
            skipped = "NO">
            ${buildableReference({ targetName: uiTestTargetName, targetUuid: uiTestTargetUuid, buildableName: `${uiTestTargetName}.xctest`, projectName: appTargetName })}
         </TestableReference>
      </Testables>
      <MacroExpansion>
         ${buildableReference({ targetName: appTargetName, targetUuid: appTargetUuid, buildableName: `${appTargetName}.app`, projectName: appTargetName })}
      </MacroExpansion>
   </TestAction>
   <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "NO"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         ${buildableReference({ targetName: appTargetName, targetUuid: appTargetUuid, buildableName: `${appTargetName}.app`, projectName: appTargetName })}
      </BuildableProductRunnable>
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Release"
      shouldUseLaunchSchemeArgsEnv = "YES"
      savedToolIdentifier = ""
      useCustomWorkingDirectory = "NO"
      debugDocumentVersioning = "YES">
   </ProfileAction>
   <AnalyzeAction
      buildConfiguration = "Debug">
   </AnalyzeAction>
   <ArchiveAction
      buildConfiguration = "Release"
      revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>
`
}

function buildableReference({ targetName, targetUuid, buildableName, projectName }) {
  return `<BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "${xmlEscape(targetUuid)}"
               BuildableName = "${xmlEscape(buildableName)}"
               BlueprintName = "${xmlEscape(targetName)}"
               ReferencedContainer = "container:${xmlEscape(projectName)}.xcodeproj">
            </BuildableReference>`
}

function trimQuotes(value) {
  return String(value || '').replace(/^"|"$/g, '')
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

module.exports = {
  buildUiTestScheme,
  copyCompanionFiles,
  inferProjectName,
  scaffoldCompanion,
}
