/**
 * Metro-level harness install (REQ-SEAM-002, REQ-SEAM-007).
 *
 * `withRnDriverHarness(config)` is the whole consumer footprint of the driver's
 * JS harness: one call in `metro.config.js`, no import in app source. Under the
 * runner's marker (`RN_E2E=1`) Metro serves a generated entry in place of the
 * app entry; that entry loads the harness first and then the real entry. With
 * the marker unset the config is returned unchanged apart from a cache-version
 * component, so a flip can never serve a stale bundle.
 *
 * Why an entry swap rather than `serializer.getModulesRunBeforeMainModule`:
 * Metro only emits run statements for modules already in the graph
 * (`metro/src/lib/getAppendScripts.js`, the `modules.some(...)` guard), so a
 * module nothing imports never reaches the bundle. Expo's own dev clients
 * request `/.expo/.virtual-metro-entry.bundle` and Expo's `rewriteRequestUrl`
 * maps it to the project entry; this helper composes after that rewrite and
 * points the request at the generated entry instead. `expo export` and
 * `export:embed` bundle the project entry directly without a request, so a
 * release artifact never carries the harness regardless of the marker.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

import { E2E_MARKER, isE2EMarked } from './e2e-marker'

export { E2E_MARKER }
/** Project-relative path of the generated entry. `.expo/` is Expo-owned and gitignored. */
export const E2E_ENTRY_RELATIVE = '.expo/rn-driver-e2e-entry.js'
const HARNESS_SPECIFIER = 'rn-driver:harness'
const APP_ENTRY_SPECIFIER = 'rn-driver:app-entry'
const VIRTUAL_ENTRY_PATHNAME = '/.expo/.virtual-metro-entry.bundle'
const URL_BASE = 'http://rn-driver.invalid'

export type MetroResolution = { readonly type: string; readonly filePath?: string }
export interface MetroResolutionContext {
  readonly originModulePath: string
  readonly resolveRequest: MetroResolveRequest
}
export type MetroResolveRequest = (
  context: MetroResolutionContext,
  moduleName: string,
  platform: string | null,
) => MetroResolution

/** The subset of a Metro config this helper reads and writes. */
export interface MetroConfigLike {
  readonly projectRoot?: string
  readonly cacheVersion?: string
  readonly server?: { readonly rewriteRequestUrl?: (url: string) => string }
  readonly resolver?: { readonly resolveRequest?: MetroResolveRequest | null }
}

/** `@expo/config/paths`, loaded from the app so the driver need not depend on it. */
export interface ExpoPaths {
  resolveEntryPoint(projectRoot: string, options?: { platform?: string }): string
  getMetroServerRoot(projectRoot: string): string
}

export interface EntryFileIo {
  existsSync(file: string): boolean
  readFileSync(file: string): string
  writeFileSync(file: string, contents: string): void
  mkdirSync(directory: string): void
}

export interface WithRnDriverHarnessOptions {
  /** Defaults to `process.env`. */
  readonly env?: Readonly<Record<string, string | undefined>>
  /** Defaults to `@expo/config/paths` resolved from the project root. */
  readonly paths?: ExpoPaths
  /** Defaults to `node:fs`. */
  readonly fs?: EntryFileIo
  /** Defaults to this package's `harness/index.ts`. */
  readonly harnessPath?: string
}

const nodeFs: EntryFileIo = {
  existsSync,
  readFileSync: (file) => readFileSync(file, 'utf8'),
  writeFileSync: (file, contents) => writeFileSync(file, contents),
  mkdirSync: (directory) => {
    mkdirSync(directory, { recursive: true })
  },
}

/** Source of the generated entry. Static: the two specifiers resolve per request. */
export function e2eEntrySource(): string {
  return [
    '// Generated by @unrulysystems/rn-playwright-driver/metro while RN_E2E=1.',
    '// Not app source: Metro serves this file in place of the app entry so the',
    '// driver harness loads first. Safe to delete; regenerated on the next start.',
    `require('${HARNESS_SPECIFIER}')`,
    `module.exports = require('${APP_ENTRY_SPECIFIER}')`,
    '',
  ].join('\n')
}

export function withRnDriverHarness<T extends MetroConfigLike>(
  config: T,
  options: WithRnDriverHarnessOptions = {},
): T {
  const env = options.env ?? process.env
  const enabled = isE2EMarked(env)
  const cacheVersion = [config.cacheVersion, enabled ? 'rn-driver-e2e' : 'rn-driver-off']
    .filter((part) => part !== undefined && part !== '')
    .join('-')
  if (!enabled) return { ...config, cacheVersion }

  const projectRoot = config.projectRoot
  if (!projectRoot) {
    throw new Error(
      'withRnDriverHarness: config.projectRoot is missing; pass the result of getDefaultConfig(__dirname).',
    )
  }
  const io = options.fs ?? nodeFs
  const paths = options.paths ?? loadExpoPaths(projectRoot)
  const harnessPath = options.harnessPath ?? defaultHarnessPath()
  const entryFile = path.join(projectRoot, E2E_ENTRY_RELATIVE)
  writeIfChanged(io, entryFile, e2eEntrySource())

  const serverRoot = paths.getMetroServerRoot(projectRoot)
  const entryBundlePath = bundlePathname(serverRoot, entryFile)
  const previousRewrite = config.server?.rewriteRequestUrl ?? ((url: string) => url)
  const rewriteRequestUrl = (url: string): string => {
    const rewritten = previousRewrite(url)
    if (!isEntryRequest(url, rewritten, projectRoot, serverRoot, paths)) return rewritten
    return replacePathname(rewritten, entryBundlePath)
  }

  const previousResolve = config.resolver?.resolveRequest ?? null
  const resolveRequest: MetroResolveRequest = (context, moduleName, platform) => {
    if (context.originModulePath === entryFile) {
      if (moduleName === HARNESS_SPECIFIER) return { type: 'sourceFile', filePath: harnessPath }
      if (moduleName === APP_ENTRY_SPECIFIER) {
        const filePath = paths.resolveEntryPoint(projectRoot, platform ? { platform } : {})
        return { type: 'sourceFile', filePath }
      }
    }
    return previousResolve
      ? previousResolve(context, moduleName, platform)
      : context.resolveRequest(context, moduleName, platform)
  }

  return {
    ...config,
    cacheVersion,
    server: { ...config.server, rewriteRequestUrl },
    resolver: { ...config.resolver, resolveRequest },
  }
}

function loadExpoPaths(projectRoot: string): ExpoPaths {
  const appRequire = createRequire(path.join(projectRoot, 'package.json'))
  try {
    return appRequire('@expo/config/paths') as ExpoPaths
  } catch (error) {
    throw new Error(
      `withRnDriverHarness: @expo/config/paths (a dependency of expo) is not resolvable from ${projectRoot}: ${String(error)}`,
      { cause: error },
    )
  }
}

function defaultHarnessPath(): string {
  const harness = path.resolve(__dirname, '../harness/index.ts')
  if (!existsSync(harness)) {
    throw new Error(`withRnDriverHarness: harness source not found at ${harness}`)
  }
  return harness
}

function writeIfChanged(io: EntryFileIo, file: string, contents: string): void {
  if (io.existsSync(file) && io.readFileSync(file) === contents) return
  io.mkdirSync(path.dirname(file))
  io.writeFileSync(file, contents)
}

function bundlePathname(serverRoot: string, file: string): string {
  const relative = path.relative(serverRoot, file).split(path.sep).join('/')
  return `/${relative.replace(/\.[cm]?[jt]sx?$/, '')}.bundle`
}

function parseUrl(url: string): { readonly parsed: URL; readonly absolute: boolean } {
  const absolute = /^[a-z][a-z0-9+.-]*:\/\//i.test(url)
  return { parsed: new URL(url, URL_BASE), absolute }
}

function replacePathname(url: string, pathname: string): string {
  const { parsed, absolute } = parseUrl(url)
  parsed.pathname = pathname
  return absolute ? parsed.toString() : `${parsed.pathname}${parsed.search}`
}

/**
 * A request is an entry request when the client asked for Expo's virtual entry, or when
 * the (already rewritten) pathname names the project entry for the request's platform.
 */
function isEntryRequest(
  originalUrl: string,
  rewrittenUrl: string,
  projectRoot: string,
  serverRoot: string,
  paths: ExpoPaths,
): boolean {
  if (parseUrl(originalUrl).parsed.pathname === VIRTUAL_ENTRY_PATHNAME) return true
  const { parsed } = parseUrl(rewrittenUrl)
  if (!parsed.pathname.endsWith('.bundle')) return false
  const platform = parsed.searchParams.get('platform')
  let entry: string
  try {
    entry = paths.resolveEntryPoint(projectRoot, platform ? { platform } : {})
  } catch {
    return false
  }
  return parsed.pathname === bundlePathname(serverRoot, entry)
}
